### ISSUE TITLE
Operator doesn't show public field if network is not specified (beta branch)

### ISSUE THREAD

**Issue by aliciafmachado** [google/kctf#137]
As the field "network" is optional, if you don't declare it, all the fields inside of it aren't declared as well. Then, if you create a custom resource without "network", everything works, but the public field shown when you get challenges is empty.
Example:
Custom Resource:

```
apiVersion: kctf.dev/v1alpha1
kind: Challenge
metadata:
  name: mychal
  namespace: mychal
spec:
  image: "some_image"
  deployed: true
  // we don't have the network part
```

Get challenges:
```
 name    health    status  deployed   public
 mychal disabled Running  true  
```
