### ISSUE TITLE
experiment with kompose as a format for multiple containers in a cluster

### ISSUE THREAD

**Issue by sirdarckcat** [google/kctf#157]
http://kompose.io would be a nice way to convert `docker-compose.yaml` files to the pod template.

instead of doing `docker build foo && docker push bar` we could do ```kompose --build local --push-image -f docker-compose.yaml``` 

one thing that we need to do, is to define the name of the image to point to the GCR repo, we can do that with: `yq -Y '.services |= with_entries(.key as $name | .value.image |= (if . != null then . else "eu.gcr.io/project/cluster-taskname-" + $name end))' docker-compose.yaml`

that transforms a docker-compose like this:
```
version: "3"
services:
  redis-master:
    build: ./redis
    ports:
      - "6379"
```

into this:
```
version: "3"
services:
  redis-master:
    build: ./redis
    ports:
      - "6379"
    image: eu.gcr.io/project/cluster-taskname-redis-master
```

We can then convert that to a spec template like this:
`kompose convert --stdout | yq -Y '.items[] | select(.kind == "Deployment") | .spec.template'`

```
metadata:
  annotations:
    kompose.cmd: kompose convert --stdout
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: redis-master
spec:
  containers:
    - image: eu.gcr.io/project/cluster-taskname-redis-master
      name: redis-master
      ports:
        - containerPort: 6379
      resources: {}
  restartPolicy: Always
```
