### ISSUE TITLE
Usage with docker-compose

### ISSUE THREAD

**Issue by tomadimitrie** [google/kctf#351]
Hi, is it possible to deploy a web challenge with multiple containers like docker-compose?

**Comment by sroettger** [comment]
It's possible, but we don't have support to build the containers automatically.
You can add additional containers under:
```yaml
spec:
  podTemplate:
    template:
      spec:
        containers:
```
