### ISSUE TITLE
custom resource specs (cpu/mem requests/limits) of healthcheck container in challenge manifest has no effect

### ISSUE THREAD

**Issue by phongvq** [google/kctf#387]
# Summary
Regardless of resources spec (cpu / mem requests / limits) of _healthcheck container_ in challenge manifest,  

```yaml
# challenge manifest

apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  annotations: {}
  name: asf
  namespace: default
status:
  health: healthy
  status: Running
spec:
  deployed: true
  healthcheck:
    enabled: true
    image: >-
      aaaa
  image: >-
     aaaa
  network:
     ports:
      - domains:
          - adsf.a.a.
        name: ext
        protocol: TCP
        targetPort: 1337
    public: false
  podTemplate:
    template:
      spec:
        containers:
          - name: challenge
            resources:
              requests:
                cpu: 1m
                memory: 1Mi
          - name: healthcheck
            resources:
              requests:
                cpu: 1m
                memory: 1Mi
```

resource spec of container in deployment is always set as below.

```yaml
# created deployment

    - name: healthcheck
      image: >-
        abc
      resources:
        limits:
          cpu: '1'
        requests:
          cpu: 50m
```

# Expected behaviour
Resource specs of healthcheck container in deployment must be same as what specified in challenge.yaml.
